# Generated by Django 4.0.2 on 2022-02-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('model_year', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fuel_type', models.CharField(choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('Other', 'Other')], default='Gasoline', max_length=10)),
                ('vehicle_type', models.CharField(choices=[('A Class Car', 'A Class Car'), ('B Class Car', 'B Class Car'), ('C Class Car', 'C Class Car'), ('S Class Car', 'S Class Car'), ('SUV', 'Suv'), ('Van', 'Van'), ('Truck', 'Truck'), ('Motorcycle', 'Motorcycle'), ('Other', 'Other')], default='C Class Car', max_length=20)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
    ]
